# Generated by Django 3.2.13 on 2022-11-06 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('전화번호', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.TextField()),
                ('Opening_hours', models.TextField()),
                ('menu', models.TextField()),
                ('price_avg', models.TextField()),
                ('day_off', models.CharField(max_length=40)),
                ('parking', models.CharField(choices=[('주차공간없음', '주차공간없음'), ('유료주차 가능', '유료주차 가능'), ('무료주차 가능', '무료주차 가능'), ('기타', '기타')], max_length=50)),
                ('category', models.CharField(choices=[('한식', '한식'), ('양식', '양식'), ('중식', '중식'), ('일식', '일식'), ('기타', '기타')], max_length=50)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='')),
                ('like_users', models.ManyToManyField(related_name='like_restaurant', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=restaurants.models.get_image_filename)),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurants')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
