# Generated by Django 3.2.13 on 2022-11-04 08:13

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantimages',
            options={},
        ),
        migrations.AlterField(
            model_name='restaurantimages',
            name='image',
            field=models.ImageField(upload_to=restaurants.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='restaurantimages',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurants'),
        ),
    ]
