# Generated by Django 3.2.13 on 2022-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='price_avg',
            field=models.CharField(choices=[('주차공간없음', '주차공간없음'), ('유료주차 가능', '유료주차 가능'), ('무료주차 가능', '무료주차 가능'), ('기타', '기타')], max_length=50),
        ),
    ]
