# Generated by Django 3.2.13 on 2022-11-02 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_auto_20221102_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='like_users',
            field=models.ManyToManyField(related_name='like_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='day_off',
            field=models.CharField(max_length=40),
        ),
    ]
