# Generated by Django 3.2.13 on 2022-11-04 08:41

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20221104_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantimages',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='restaurantimages',
            name='image',
            field=models.ImageField(blank=True, upload_to=restaurants.models.get_image_filename),
        ),
    ]
