# Generated by Django 3.2.13 on 2022-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurants_price_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='price_avg',
            field=models.CharField(choices=[('만원 미만', '만원 미만'), ('1만원-2만원', '1만원-2만원'), ('2만원-3만원', '2만원-3만원'), ('3만원-5만원', '3만원-5만원'), ('5만원 이상', '5만원 이상')], max_length=50),
        ),
    ]
