# Generated by Django 3.2.13 on 2022-11-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20221104_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_phone_number',
            new_name='전화번호',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='parking',
            field=models.CharField(choices=[('무료', '한식'), ('양식', '양식'), ('중식', '중식'), ('일식', '일식'), ('기타', '기타')], max_length=50),
        ),
    ]
