# Generated by Django 3.2.13 on 2022-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurants_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
