# Generated by Django 3.2.13 on 2022-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20221105_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_phone_number',
            new_name='전화번호',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='parking',
            field=models.CharField(choices=[('주차공간없음', '주차공간없음'), ('유료주차 가능', '유료주차 가능'), ('무료주차 가능', '무료주차 가능'), ('기타', '기타')], max_length=50),
        ),
    ]
