# Generated by Django 3.2.13 on 2022-11-06 05:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20221106_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=''),
        ),
    ]
