# Generated by Django 3.2.13 on 2022-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.CharField(choices=[('KR', '한식'), ('WS', '양식'), ('CH', '중식'), ('JP', '일식'), ('Etc', '기타')], max_length=50),
        ),
    ]
