# Generated by Django 3.2.13 on 2022-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.CharField(choices=[('한식', '한식'), ('양식', '양식'), ('중식', '중식'), ('일식', '일식'), ('기타', '기타')], max_length=50),
        ),
    ]
