# Generated by Django 3.2.13 on 2022-11-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurants_category'),
        ('restaurants', '0008_restaurants_hits'),
    ]

    operations = [
    ]
