# Generated by Django 3.2.13 on 2022-11-03 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
